### ISSUE TITLE
Send Receive is better than clone

### ISSUE THREAD

**Issue by KreizIT** [clinta/clinta.github.io#4]
https://github.com/clinta/clinta.github.io/blob/54b849e6fec70856d1ccdceaa82fd46b3e122743/freebsd-jails-the-hard-way/index.html#L232

Zfs clone maintain relationship betwin snapshot and dataset. If you need to update skeleton you cannot remove this snapshot to recreate it.

As thinjail1 will live it's own life, should be better to do : 
`zfs send zroot/jails/templates/skeleton-10.2-RELEASE@skeleton | zfs received zroot/jails/thinjails/thinjail1`

Also as received create also a snapshot you should issu a `zfs destroy zroot/jails/thinjails/thinjail1@skeleton` to forget about this snapshot.

**Comment by clinta** [comment]
You can remove the relationship between the parent snapshot and the clone
with zfs promote. Once you promote the child dataset you can delete the
parent  snapshot all without duplicating the data blocks like a send |
receive does.
